### PR TITLE
Node 14 + loosen peer dependency

### PR DESCRIPTION
**Pull request by phawxby**

### CODE REVIEW

**Review by AndrewLeedham — APPROVED** [review]
This is fine, but the publish process is broken. @tinytim84 where are you with that?

**Comment by tinytim84** [comment]
> This is fine, but the publish process is broken. @tinytim84 where are you with that?

They've made a new release.  Do you want me to add it to this and we can give it a try with this update?

**Comment by AndrewLeedham** [comment]
> They've made a new release. Do you want me to add it to this and we can give it a try with this update?

Yup.

**Comment by AndrewLeedham** [comment]
@phawxby I'll merge this once the publishing process is fixed.

**Pull request merged**
