### PR TITLE
release: windows file path fix and other updates

### PR DESCRIPTION
**Pull request by tinytim84**

### CODE REVIEW

**Comment by AndrewLeedham** [comment]
@tinytim84 Have you tried the next release locally? `yarn global upgrade @xerox/cli@next`

**Comment by tinytim84** [comment]
> @tinytim84 Have you tried the next release locally? `yarn global upgrade @xerox/cli@next`

Not by installing it. I just added the same code to the js file in `node_modules`. I'll check this now though.

**Comment by tinytim84** [comment]
> @tinytim84 Have you tried the next release locally? `yarn global upgrade @xerox/cli@next`

I added it here:
image
and it built fine.

**Comment by AndrewLeedham** [comment]
Did you run `yarn cli:setup`?

**Comment by tinytim84** [comment]
> Did you run `yarn cli:setup`?

I ran `yarn` and saw `success Installed "@xerox/cli@1.1.1-next.0"` in the console.

**Comment by tinytim84** [comment]
I don't need to update anything in XDS for this do I?

**Review by AndrewLeedham — APPROVED** [review]

**Pull request merged**
