### PR TITLE
fix: make refactor visible

### PR DESCRIPTION
**Pull request by phawxby**
It's hidden by default.
https://github.com/conventional-changelog/conventional-changelog-config-spec/blob/master/versions/2.1.0/schema.json#L24

Be more explicit with the others for safety.

### CODE REVIEW

**Review by AndrewLeedham — COMMENTED** [review]
Should we just `un-hide` all of them?

**Comment by phawxby** [comment]
I guess we could, would that not make for a very noisy change log?

**Comment by AndrewLeedham** [comment]
It is still only the PR titles assuming squash and merge, so would be useful information IMO

**Comment by phawxby** [comment]
There we go

**Review by AndrewLeedham — APPROVED** [review]

**Pull request merged**
